'use strict';

module.exports = {
  plugins: ['promise'],
  extends: ['eslint:recommended', 'plugin:promise/recommended'],
  env: {
    es2020: true,
  },
  rules: {
    'sort-imports': 1,
    'no-console': 1,
    'no-else-return': 1,
    'strict': 2,
    'eqeqeq': [2, 'smart'],
    'curly': [2, 'all'],
    'dot-notation': [2, { allowKeywords: true, allowPattern: '' }],
    'no-alert': 2,
    'no-caller': 2,
    'no-div-regex': 2,
    'no-eval': 2,
    'no-extend-native': 2,
    'no-extra-bind': 2,
    'no-floating-decimal': 2,
    'no-implied-eval': 2,
    'no-iterator': 2,
    'no-labels': 2,
    'no-lone-blocks': 2,
    'no-loop-func': 2,
    'no-multi-spaces': 2,
    'no-multi-str': 2,
    'no-new-func': 2,
    'no-new-wrappers': 2,
    'no-new': 2,
    'no-octal-escape': 2,
    'no-proto': 2,
    'no-return-assign': 2,
    'no-script-url': 2,
    'no-self-compare': 2,
    'no-sequences': 2,
    'no-throw-literal': 2,
    'radix': 2,
    'vars-on-top': 2,
    'wrap-iife': [2, 'inside'],
    'yoda': [2, 'never'],
    'no-label-var': 2,
    'no-shadow': 2,
    'camelcase': [2, { properties: 'always' }],
    'new-parens': 2,
    'no-array-constructor': 2,
    'no-continue': 2,
    'no-lonely-if': 2,
    'no-multiple-empty-lines': [2, { max: 2 }],
    'no-new-object': 2,
    'func-call-spacing': 2,
    'no-trailing-spaces': 2,
    'no-unneeded-ternary': 2,
    'one-var': [2, 'never'],
    'operator-assignment': [2, 'always'],
    'padded-blocks': [1, 'never'],
    'padding-line-between-statements': [
      'warn',
      { blankLine: 'always', prev: ['const', 'let', 'var'], next: '*' },
      { blankLine: 'always', prev: '*', next: ['return', 'if', 'do'] },
      {
        blankLine: 'any',
        prev: ['const', 'let', 'var'],
        next: ['const', 'let', 'var'],
      },
    ],
    'quote-props': [2, 'consistent-as-needed'],
    'semi-spacing': [2, { before: false, after: true }],
    'space-before-blocks': [2, 'always'],
    'space-in-parens': [2, 'never'],
    'space-infix-ops': 2,
    'keyword-spacing': ['error', { before: true, after: true }],
    'spaced-comment': [2, 'always'],
    'arrow-parens': [2, 'always'],
    'generator-star-spacing': [2, 'after'],
    'no-var': 2,
    'object-shorthand': ['error', 'always', { avoidQuotes: true }],
    'prefer-rest-params': 2,
    'prefer-spread': 2,
    'yield-star-spacing': [2, 'after'],
    'prefer-const': 2,
    'no-confusing-arrow': 2,
    'no-template-curly-in-string': 2,
    'require-await': 'error',
    'prefer-destructuring': 'error',
    'rest-spread-spacing': 'error',
    'prefer-template': 'error',
    'no-return-await': 'warn',
  },
};
