'use strict';

module.exports = {
  'extends': [
    'eslint:recommended'
  ],
  'plugins': [
  	'promise'
  ],
  'parser': 'babel-eslint',
  'globals': {
    '__APP_ROOT__': true,
    '__API_ROOT__': true,
    '__LOAD_BALANCER_URL__': true
  },
  'rules': {
    /* Possible Errors */
    'comma-dangle': 0,
    // 'no-cond-assign': [2, 'except-parens'], // disallow assignment operators in conditional expressions
    'no-console': 0,
    'no-constant-condition': 2,
    'no-control-regex': 2,
    'no-debugger': 2,
    'no-dupe-args': 2,
    'no-dupe-keys': 2,
    'no-duplicate-case': 0,
    'no-empty-character-class': 2,
    'no-empty': 2,
    'no-ex-assign': 2,
    'no-extra-boolean-cast': 2,
    'no-extra-parens': 0,
    'no-extra-semi': 2,
    'no-func-assign': 2,
    'no-inner-declarations': [2, 'functions'],
    'no-invalid-regexp': 2,
    'no-irregular-whitespace': 2,
    'no-negated-in-lhs': 2,
    'no-obj-calls': 2,
    'no-regex-spaces': 2,
    'no-reserved-keys': 0,
    'no-sparse-arrays': 2,
    'no-unexpected-multiline': 2,
    'no-unreachable': 2,
    'use-isnan': 2,
    'valid-jsdoc': 0,
    'valid-typeof': 2,

    /* Best Practices */
    'accessor-pairs': 0,
    'block-scoped-var': 0, // see Babel section
    'complexity': 0,
    'consistent-return': 2,
    'curly': [2, 'all'],
    'default-case': 0,
    'dot-notation': [2, { 'allowKeywords': true, 'allowPattern': '' }],
    'dot-location': [2, 'property'],
    'eqeqeq': 2,
    'guard-for-in': 0,
    'no-alert': 2,
    'no-caller': 2,
    'no-div-regex': 2,
    'no-else-return': 2,
    'no-empty-label': 0,
    'no-eq-null': 0,
    'no-eval': 2,
    'no-extend-native': 2,
    'no-extra-bind': 2,
    'no-fallthrough': 0,
    'no-floating-decimal': 2,
    'no-implied-eval': 2,
    'no-iterator': 2,
    'no-labels': 2,
    'no-lone-blocks': 2,
    'no-loop-func': 2,
    'no-multi-spaces': 2,
    'no-multi-str': 2,
    'no-native-reassign': 2,
    'no-new-func': 2,
    'no-new-wrappers': 2,
    'no-new': 2,
    'no-octal-escape': 2,
    'no-octal': 2,
    'no-param-reassign': 0,
    'no-process-env': 0,
    'no-proto': 2,
    'no-redeclare': 2,
    'no-return-assign': 2,
    'no-script-url': 2,
    'no-self-compare': 2,
    'no-sequences': 2,
    'no-throw-literal': 2,
    'no-unused-expressions': 0,
    'no-void': 0,
    'no-warning-comments': [0, { 'terms': ['todo', 'tofix'], 'location': 'start' }],
    'no-with': 2,
    'radix': 2,
    'vars-on-top': 2,
    'wrap-iife': [2, 'inside'],
    'yoda': [2, 'never'],

    /* Strict Mode */
    'strict': [0, 'never'],

    /* Variables */
    // 'init-declarations': 0,
    'no-catch-shadow': 0,
    'no-delete-var': 2,
    'no-label-var': 2,
    'no-shadow-restricted-names': 2,
    'no-shadow': 2,
    'no-undef-init': 2,
    'no-undef': 2,
    'no-undefined': 2,
    'no-unused-vars': [2, { 'vars': 'local', 'args': 'after-used' }],
    'no-use-before-define': 2,

    /* Node.js */
    'handle-callback-err': 2,
    'no-mixed-requires': 2,
    'no-new-require': 2,
    'no-path-concat': 2,
    'no-process-exit': 2,
    'no-restricted-modules': [2, ''], // add any unwanted Node.js core modules
    'no-sync': 2,
    // 'callback-return': 0,

    /* Stylistic Issues */
    'array-bracket-spacing': [2, 'never'],
    'brace-style': [2, '1tbs', { 'allowSingleLine': true }],
    'camelcase': [2, { 'properties': 'always' }],
    'comma-spacing': [2, { 'before': false, 'after': true }],
    'comma-style': [2, 'last'],
    'computed-property-spacing': 0,
    'consistent-this': 0,
    'eol-last': 2,
    'func-names': 0,
    'func-style': 0,
    'indent': ['error', 2, { SwitchCase: 1 }],
    'key-spacing': [2, { 'beforeColon': false, 'afterColon': true }],
    'linebreak-style': 0,
    'max-nested-callbacks': ['error', 3],
    'new-cap': 0, // see Babel section
    'new-parens': 2,
    'newline-after-var': 0,
    'no-array-constructor': 2,
    'no-continue': 2,
    'no-inline-comments': 0,
    'no-lonely-if': 2,
    'no-mixed-spaces-and-tabs': 2,
    'no-multiple-empty-lines': [2, { 'max': 2 }],
    'no-nested-ternary': 0,
    'no-new-object': 2,
    'no-spaced-func': 2,
    'no-ternary': 0,
    'no-trailing-spaces': 2,
    'no-underscore-dangle': 0,
    'no-unneeded-ternary': 2,
    'object-curly-spacing': [2, 'always'], // see Babel section
    'one-var': [2, 'never'],
    'operator-assignment': [2, 'always'],
    'padded-blocks': [0, 'never'],
    'padding-line-between-statements': [
      "error",
      { blankLine: "always", prev: ["const", "let", "var"], next: "*"},
      { blankLine: "always", prev: "*", next: ["return", "if", "do"]},
      { blankLine: "any",    prev: ["const", "let", "var"], next: ["const", "let", "var"]},
    ],
    'quote-props': [0, 'as-needed'],
    'quotes': ['error', 'single', { 'allowTemplateLiterals': true }],
    'semi-spacing': [2, { 'before': false, 'after': true }],
    'semi': [2, 'always'],
    'sort-vars': 0,
    'space-after-keywords': 0,
    'space-before-blocks': [2, 'always'],
    'space-before-function-paren': [2, 'never'],
    'space-in-parens': [2, 'never'],
    'space-infix-ops': 2,
    'keyword-spacing': ['error', { 'before': true, 'after': true }],
    'space-unary-ops': 0,
    'spaced-comment': [2, 'always'],
    'wrap-regex': 2,

    /* ECMAScript 6 */
    // 'arrow-body-style': 0,
    'arrow-parens': [2, 'always'], // TODO(philipwalton): technically arrow
                                   // parens are optional but recommended.
                                   // ESLint doesn't support a *consistent*
                                   // setting so "always" is used.
    // 'arrow-spacing': 0,
    'constructor-super': 2, // eslint:recommended
    'generator-star-spacing': [2, 'after'],
    // 'no-const-assign': 0, // eslint:recommended
    // 'no-dupe-class-members': 0, // eslint:recommended
    // 'no-duplicate-imports': 0,
    'no-new-symbol': 2, // eslint:recommended
    // 'no-restricted-imports': 0,
    'no-this-before-super': 2,  // eslint:recommended
    // 'no-useless-computed-key': 0,
    // 'no-useless-constructor': 0,
    // 'no-useless-rename': 0,
    'no-var': 2,
    // 'object-shorthand': 0,
    // 'prefer-arrow-callback': 0,
    // 'prefer-numeric-literals': 0,
    // 'prefer-reflect': 0,
    'prefer-rest-params': 2,
    'prefer-spread': 2,
    'prefer-template': 2,
    // 'require-yield': 2, // eslint:recommended
    'rest-spread-spacing': 2,
    // 'sort-imports': 0,
    // 'symbol-description': 0,
    // 'template-curly-spacing': 0,
    'yield-star-spacing': [2, 'after'],
    'prefer-const': 2,
    // 'no-class-assign': 2, // disallow reassigning class members,
    'no-confusing-arrow': 2,

    /* Legacy */
    'max-depth': [0, 3],
    'max-len': [2, 150, 2],
    'max-params': ['error', 4],
    'max-statements': ['error', 50],
    'no-bitwise': 2,
    'no-plusplus': 0,

    /* Promise */
    'promise/always-return': 'off',
    'promise/no-return-wrap': 'error',
    'promise/param-names': 'error',
    'promise/catch-or-return': 'error',
    'promise/no-native': 'off',
    'promise/no-nesting': 'warn',
    'promise/no-promise-in-callback': 'warn',
    'promise/no-callback-in-promise': 'warn',
    'promise/avoid-new': 'warn'
  }
};
